// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/data"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/translator"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}

	// Greeter 相关
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	articleRepo := data.NewArticleRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, articleRepo)
	greeterService := service.NewGreeterService(greeterUsecase)

	// Dictionary 相关
	dictionaryRepo := data.NewDictionaryRepo(dataData, logger)
	wordRepo := data.NewWordRepo(dataData, logger)
	uploadTaskRepo := data.NewUploadTaskRepo(dataData, logger)
	translatorImpl := translator.NewYoudaoTranslator("", "")
	dictionaryUseCase := biz.NewDictionaryUseCase(dictionaryRepo, wordRepo, uploadTaskRepo, translatorImpl)
	dictionaryService := service.NewDictionaryService(dictionaryUseCase, logger)

	// Learning 相关
	learnRecordRepo := data.NewLearnRecordRepo(dataData, logger)
	learningUseCase := biz.NewLearningUseCase(wordRepo, learnRecordRepo, dictionaryRepo)
	learningService := service.NewLearningService(learningUseCase, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	refreshTokenRepo := data.NewRefreshTokenRepo(dataData, logger)
	authUseCase := biz.NewAuthUseCase(userRepo, refreshTokenRepo)
	authService := service.NewAuthService(authUseCase)

	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, dictionaryService, learningService, authService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
